---
name: Generate schemas pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean package
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add AnalysisChain AnalysisModule BinaryFile CA CLI DataHistory
          git add Editor MLI OME OMERO ROI SA SPW STD Transforms index.html
          git commit -m "Generate Schemas pages" || echo "No changes to commit"
      - name: Push changes
        if: ${{ github.event_name == 'push' }}
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
